# REDLINE Simple Docker Compose Configuration
# No nginx-proxy, no dependencies, just the web app

version: '3.8'

services:
  redline-web:
    build:
      context: .
      dockerfile: Dockerfile
    image: redline-web:latest
    container_name: redline-web-simple
    restart: unless-stopped
    
    # Ports - direct access, no proxy
    ports:
      - "8080:8080"    # Flask web app
    
    # Environment variables
    environment:
      - FLASK_APP=web_app.py
      - FLASK_ENV=production
      - HOST=0.0.0.0
      - PORT=8080
    
    # Volumes
    volumes:
      - ./data:/opt/redline/data
      - ./logs:/var/log/redline
      - ./config:/opt/redline/config
    
    # Working directory
    working_dir: /opt/redline
    
    # Health check
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

# Networks
networks:
  default:
    driver: bridge
