# Docker Compose using system packages
version: '3.8'

services:
  redline-system:
    build:
      context: .
      dockerfile: Dockerfile.system-packages
    image: redline-system:latest
    container_name: redline-system
    restart: unless-stopped
    
    # Ports - direct Flask access
    ports:
      - "8080:8080"
    
    # Environment variables
    environment:
      - FLASK_APP=web_app.py
      - FLASK_ENV=production
      - HOST=0.0.0.0
      - PORT=8080
    
    # Working directory
    working_dir: /opt/redline
    
    # Simple command - just run Flask directly
    command: python3 web_app.py
