name: redline
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pandas>=2.0.0
  - numpy>=1.24.0
  - pyarrow>=10.0.0
  - polars>=0.20.0
  - duckdb>=0.8.0
  - yfinance>=0.2.0
  - scikit-learn>=1.3.0
  - matplotlib>=3.7.0
  - seaborn>=0.12.0
  - requests>=2.31.0
  - configparser>=5.3.0
  - pytest>=7.0.0
  - black>=23.0.0
  - flake8>=6.0.0
  - pip
  - pip:
    - openpyxl>=3.1.0
    - xlsxwriter>=3.1.0
