"""Initial schema: users, user_hours, sessions, payments, logs

Revision ID: ae10e33ab1b0
Revises: 
Create Date: 2025-12-19 19:27:05.603315

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae10e33ab1b0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('company', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('access_logs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=True),
    sa.Column('endpoint', sa.String(), nullable=False),
    sa.Column('method', sa.String(), nullable=False),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('user_agent', sa.String(), nullable=True),
    sa.Column('response_status', sa.Integer(), nullable=True),
    sa.Column('response_time_ms', sa.Integer(), nullable=True),
    sa.Column('access_time', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_access_logs_endpoint', 'access_logs', ['endpoint'], unique=False)
    op.create_index('idx_access_logs_time', 'access_logs', ['access_time'], unique=False)
    op.create_index('idx_access_logs_user', 'access_logs', ['user_id'], unique=False)
    op.create_table('payment_history',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('stripe_session_id', sa.String(), nullable=True),
    sa.Column('payment_id', sa.String(), nullable=True),
    sa.Column('hours_purchased', sa.Float(), nullable=False),
    sa.Column('amount_paid', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(), nullable=True),
    sa.Column('payment_status', sa.String(), nullable=True),
    sa.Column('payment_date', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_payment_history_date', 'payment_history', ['payment_date'], unique=False)
    op.create_index('idx_payment_history_user', 'payment_history', ['user_id'], unique=False)
    op.create_table('usage_history',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=True),
    sa.Column('hours_deducted', sa.Float(), nullable=False),
    sa.Column('deduction_time', sa.DateTime(), nullable=False),
    sa.Column('hours_remaining_before', sa.Float(), nullable=True),
    sa.Column('hours_remaining_after', sa.Float(), nullable=True),
    sa.Column('api_endpoint', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_usage_history_time', 'usage_history', ['deduction_time'], unique=False)
    op.create_index('idx_usage_history_user', 'usage_history', ['user_id'], unique=False)
    op.create_table('usage_sessions',
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('total_hours', sa.Float(), nullable=True),
    sa.Column('total_seconds', sa.Float(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('session_id')
    )
    op.create_index('idx_usage_sessions_start', 'usage_sessions', ['start_time'], unique=False)
    op.create_index('idx_usage_sessions_user', 'usage_sessions', ['user_id'], unique=False)
    op.create_table('user_hours',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('hours_remaining', sa.Float(), nullable=True),
    sa.Column('total_hours_purchased', sa.Float(), nullable=True),
    sa.Column('total_hours_used', sa.Float(), nullable=True),
    sa.Column('last_deduction_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index('idx_user_hours_user', 'user_hours', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_user_hours_user', table_name='user_hours')
    op.drop_table('user_hours')
    op.drop_index('idx_usage_sessions_user', table_name='usage_sessions')
    op.drop_index('idx_usage_sessions_start', table_name='usage_sessions')
    op.drop_table('usage_sessions')
    op.drop_index('idx_usage_history_user', table_name='usage_history')
    op.drop_index('idx_usage_history_time', table_name='usage_history')
    op.drop_table('usage_history')
    op.drop_index('idx_payment_history_user', table_name='payment_history')
    op.drop_index('idx_payment_history_date', table_name='payment_history')
    op.drop_table('payment_history')
    op.drop_index('idx_access_logs_user', table_name='access_logs')
    op.drop_index('idx_access_logs_time', table_name='access_logs')
    op.drop_index('idx_access_logs_endpoint', table_name='access_logs')
    op.drop_table('access_logs')
    op.drop_table('users')
    # ### end Alembic commands ###
